const translationMap = new Map<string, string>([
    ["en", "en"],
    ["zh-CN", "zh-Hans"],
    ["zh-TW", "zh-Hant"],
    ["ja", "ja"],
    ["sq", "sq"],
    ["ar", "ar"],
    ["am", "am"],
    ["az", "az"],
    ["ga", "ga"],
    ["et", "et"],
    ["bg", "bg"],
    ["is", "is"],
    ["pl", "pl"],
    ["bs", "bs"],
    ["fa", "fa"],
    ["af", "af"],
    ["da", "da"],
    ["de", "de"],
    ["ru", "ru"],
    ["fr", "fr"],
    ["tl", "tl"],
    ["fi", "fil"],
    ["km", "km"],
    ["ka", "ka"],
    ["gu", "gu"],
    ["kk", "kk"],
    ["ko", "ko"],
    ["nl", "nl"],
    ["gl", "gl"],
    ["ca", "ca"],
    ["cs", "cs"],
    ["kn", "kn"],
    ["hr", "hr"],
    ["lv", "lv"],
    ["lo", "lo"],
    ["lt", "lt"],
    ["rw", "rw"],
    ["ro", "ro"],
    ["mt", "mt"],
    ["mr", "mr"],
    ["ml", "ml"],
    ["ms", "ms"],
    ["mk", "mk"],
    ["mn", "mn-Cyrl"],
    ["bn", "bn"],
    ["my", "my"],
    ["zu", "zu"],
    ["ne", "ne"],
    ["no", "nb"],
    ["pt", "pt"],
    ["ps", "ps"],
    ["sv", "sv"],
    ["sr", "sr-Cyrl"],
    ["si", "si"],
    ["sk", "sk"],
    ["sl", "sl"],
    ["sw", "sw"],
    ["so", "so"],
    ["te", "te"],
    ["ta", "ta"],
    ["th", "th"],
    ["tr", "tr"],
    ["cy", "cy"],
    ["ur", "ur"],
    ["uk", "uk"],
    ["uz", "uz"],
    ["es", "es"],
    ["iw", "he"],
    ["el", "el"],
    ["hu", "hu"],
    ["it", "it"],
    ["hi", "hi"],
    ["id", "id"],
    ["vi", "vi"],
])

const voiceMap = new Map<string, string>([
    ["en", "en-US-AvaMultilingualNeural"],
    ["zh-CN", "zh-CN-XiaoxiaoNeural"],
    ["zh-TW", "zh-TW-HsiaoChenNeural"],
    ["ja", "ja-JP-NanamiNeural"],
    ["ar", "ar-DZ-AminaNeural"],
    ["am", "am-ET-AmehaNeural"],
    ["az", "az-AZ-BanuNeural"],
    ["ga", "ga-IE-OrlaNeural"],
    ["et", "et-EE-AnuNeural"],
    ["bg", "bg-BG-KalinaNeural"],
    ["is", "is-IS-GudrunNeural"],
    ["pl", "pl-PL-ZofiaNeural"],
    ["bs", "bs-BA-VesnaNeural"],
    ["fa", "fa-IR-DilaraNeural"],
    ["af", "af-ZA-AdriNeural"],
    ["da", "da-DK-ChristelNeural"],
    ["de", "de-AT-IngridNeural"],
    ["ru", "ru-RU-SvetlanaNeural"],
    ["fr", "fr-BE-CharlineNeural"],
    ["tl", "fil-PH-BlessicaNeural"],
    ["fi", "fi-FI-NooraNeural"],
    ["km", "km-KH-SreymomNeural"],
    ["ka", "ka-GE-EkaNeural"],
    ["gu", "gu-IN-DhwaniNeural"],
    ["kk", "kk-KZ-AigulNeural"],
    ["ko", "ko-KR-SunHiNeural"],
    ["nl", "nl-BE-DenaNeural"],
    ["gl", "gl-ES-SabelaNeural"],
    ["ca", "ca-ES-JoanaNeural"],
    ["cs", "cs-CZ-VlastaNeural"],
    ["kn", "kn-IN-SapnaNeural"],
    ["hr", "hr-HR-GabrijelaNeural"],
    ["lv", "lv-LV-EveritaNeural"],
    ["lo", "lo-LA-KeomanyNeural"],
    ["lt", "lt-LT-OnaNeural"],
    ["rw", "lt-LT-OnaNeural"],
    ["ro", "ro-RO-AlinaNeural"],
    ["mt", "mt-MT-GraceNeural"],
    ["mr", "mr-IN-AarohiNeural"],
    ["ml", "ml-IN-SobhanaNeural"],
    ["ms", "ms-MY-YasminNeural"],
    ["mk", "mk-MK-MarijaNeural"],
    ["mn", "mn-MN-YesuiNeural"],
    ["bn", "bn-IN-TanishaaNeural"],
    ["my", "my-MM-NilarNeural"],
    ["zu", "zu-ZA-ThandoNeural"],
    ["ne", "ne-NP-HemkalaNeural"],
    ["no", "nb-NO-FinnNeural"],
    ["pt", "pt-BR-ThalitaNeural"],
    ["ps", "ps-AF-LatifaNeural"],
    ["sv", "sv-SE-SofieNeural"],
    ["sr", "sr-RS-SophieNeural"],
    ["si", "si-LK-ThiliniNeural"],
    ["sk", "sk-SK-ViktoriaNeural"],
    ["sl", "sl-SI-PetraNeural"],
    ["sw", "sw-KE-ZuriNeural"],
    ["so", "so-SO-UbaxNeural"],
    ["te", "te-IN-ShrutiNeural"],
    ["ta", "ta-IN-PallaviNeural"],
    ["th", "th-TH-PremwadeeNeural"],
    ["tr", "tr-TR-EmelNeural"],
    ["cy", "cy-GB-NiaNeural"],
    ["ur", "ur-IN-GulNeural"],
    ["uk", "uk-UA-PolinaNeural"],
    ["uz", "uz-UZ-MadinaNeural"],
    ["es", "es-AR-ElenaNeural"],
    ["iw", "he-IL-HilaNeural"],
    ["el", "el-GR-AthinaNeural"],
    ["hu", "hu-HU-NoemiNeural"],
    ["it", "it-IT-DiegoNeural"],
    ["hi", "hi-IN-SwaraNeural"],
    ["id", "id-ID-GadisNeural"],
    ["vi", "vi-VN-HoaiMyNeural"],
])

const posTagMap = new Map<string, string>([
    ["ADJ", "Adjectives"],
    ["ADV", "Adverbs"],
    ["CONJ", "Conjunctions"],
    ["DET", "Determiners"],
    ["MODAL", "Verbs"],
    ["NOUN", "Nouns"],
    ["PREP", "Prepositions"],
    ["PRON", "Pronouns"],
    ["VERB", "Verbs"],
    ["OTHER", "Other"],
])

const parseTranslation = (value: string) => {
    let key = value
    translationMap.forEach((k, v) => {
        if (v === value) key = k
    })
    return key
}

const parseVoice = (value: string) => {
    let key = value
    voiceMap.forEach((k, v) => {
        if (v === value) key = k
    })
    return key
}

export {
    translationMap,
    voiceMap,
    posTagMap,
    parseTranslation,
    parseVoice,
}