name: compile and package

on: workflow_dispatch

jobs:
  compile-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0
    
      - name: Setup Node
        uses: actions/setup-node@v3.5.1
        
      - name: Run npm Scripts
        run: |
          npm install
          npm run package
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: vscode-translation
          path: build/*
