name: compile and package

on: workflow_dispatch

jobs:
  compile-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@latest
    
      - name: Setup Node
        uses: actions/setup-node@latest
        
      - name: Run npm Scripts
        run: |
          npm install
          npm run package
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@latest
        with:
          name: vscode-translation
          path: build/*
    
    
