name: package

on: workflow_dispatch

jobs:
  package:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.6.0
    
      - name: Setup Node
        uses: actions/setup-node@v3.5.1
        
      - name: Run npm Scripts
        run: |
          npm install
          npm run package
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          path: build/*
    
    
